README.md
`python -m baselines.deepq.experiments.download_model` becomes `python -m baselines.deepq.experiments.atari.download_model`
=> Correct path to script "download_model"

baselines/deepq/simple.py
It seems that the weights retrieved from the replay buffer are not applied when training the model. Is there any reason for that or am I missing something?
In any case, I have added a parameter in order for them to be used; just in case it is useful.
=> Effectively apply weights from the replay buffer

baselines/ppo1/cnn_policy.py, baselines/ppo1/mlp_policy.py, baselines/trpo_mpi/nosharing_cnn_policy.py
Fix the warning:
> WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
[2017-08-26 19:01:12,395] VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
=> Deprecated VARIABLES -> GLOBAL_VARIABLES.

baselines/a2c/a2c.py, baselines/acktr/acktr_disc.py
Before this fix, the frame-stacking methods in ACKTR/A2C assume the observation space is grey scale (like deepmind-wrapped atari).
@joschu Please review and let me know if I should add tests.
=> Fixes frame stacking in A2C and ACKTR for multi-channel observations

baselines/ppo2/README.md
Only found this typo after I copy-pasted the command and the GPU OOM'd even though the ppo2 code has the TF GPU growth option enabled.
=> Call ppo2 and not ppo1 in ppo2 README.md

baselines/deepq/replay_buffer.py
The `ReplayBuffer` class docstring stated that it implemented a prioritized replay buffer, and not the vanilla version.
=> Docstring fix

baselines/a2c/run_atari.py, baselines/acktr/run_atari.py, baselines/acktr/run_mujoco.py, baselines/ppo1/run_atari.py, baselines/ppo1/run_mujoco.py, baselines/trpo_mpi/run_atari.py, baselines/trpo_mpi/run_mujoco.py
This is a Python 3-only library. A shebang with `#!/usr/bin/env python`
will launch python2 on many systems which do not have python3
installed. Setting the shebang to `#!/usr/bin/env python3` will show a
useful error on systems without Python 3.
=> Force shebang lines to Python 3

baselines/acer/policies.py
The `act` keyword was removed from baselines.a2c.utils.fc in commit 9fa8e1b.
=> Fix fc call in AcerLstmPolicy

baselines/a2c/a2c.py
Calling make_path(save_path) creates save_path as a folder instead of a file.
But joblib.dump expects save_path to be a file. Thus it was throwing error.
Changing make_path's argument to osp.dirname(save_path) fixes the problem.
Note: Tested on Windows 10. Python 3.5.4.
=> Bug fix in saving a2c model.

baselines/ddpg/training.py
The variable `t` here should be `t_train`. `t` is invariant for this loop, so `t % param_noise_adaption_interval == 0` will evaluate to the same thing each time. For the default values of the parameters `param_noise_adaption_interval` (50) and `nb_rollout_steps` (100), this causes the code to adapt the scale of the parameter space noise in every single training step, which is correct but slow.
(For other values of the parameters, the adaptation won't happen for long periods of time, which is a problem.)
=> Fix bug in DDPG parameter space noise adaptation

baselines/her/experiment/plot.py, baselines/her/experiment/train.py
- Fixes the plotting script (https://github.com/openai/baselines/issues/311)
- Adds a warning that `--num_cpu` is important for reproducing results (https://github.com/openai/baselines/issues/314)
=> Minor fixes to HER release

setup.py
as pointed out in https://github.com/openai/baselines/issues/342, opencv-python dependency was missing
=> add opencv-python to the dependencies

baselines/gail/dataset/mujoco_dset.py
Currently all but the first episode are zeroed out due to a whitespace error.
I'm confused why ```flatten``` has been implemented with a for-loop at all, I think it can be replaced directly with a NumPy reshape command. But I don't understand enough of the surrounding code to be confident this wouldn't break anything.
Request review from @andrewliao11
=> GAIL: bugfix in dataset loading

baselines/deepq/build_graph.py, baselines/deepq/deepq.py, baselines/run.py
Solves issue in run script for classic control (#504).
Adds `bench.Monitor` to the classic control envs so PPO reports rewards (#505).
Fixes issues with serializing deepq models (#506).
=> Several bugfixes for #504, #505, #506 related to Classic Control and deepq

baselines/deepq/experiments/run_atari.py
`deepq.learn()` in [run_atari.py](https://github.com/openai/baselines/blob/master/baselines/deepq/experiments/run_atari.py) requires network name and network_kwargs, not `deepq.models.cnn_to_mlp` object.
=> Fix argument error in deepq

baselines/acktr/acktr_cont.py, baselines/acktr/acktr_disc.py, baselines/acktr/kfac.py, baselines/acktr/value_functions.py
Fix 'async' is a reserved word in Python >= 3.7 (#495). Instead `async`, `async_` is used in `baselines.acktr.kfac.KfacOptimizer()`.
=> fix 'async' is a reserved word in Python >= 3.7 (#495)

baselines/run.py
I encountered the following error when running `python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=1000 --save_path=./pong_1K_ppo2` on macos with Python3.5.3:
```
File "/Users/xxxx/p/baselines/baselines/common/cmd_util.py", line 41, in make_vec_env
if num_env > 1: return SubprocVecEnv([make_env(i + start_index) for i in range(num_env)])
TypeError: 'float' object cannot be interpreted as an integer
```
It's because I didn't specify `--num_env`, so it defaults to `ncpu / 2` which is a float.
=> ncpu needs to be an integer.

README.md
In my experiments, mean reward per episode can only reach 20 instead of 5k.
=> Fix mean reward per episode after training Pong.

baselines/her/rollout.py
In the HER RolloutWorker there is an if statement which catches if the environment returned any nan values in the observation. If there are, it calls logger.warning(). But the logger does not have a warning() function. I believe it is meant to be warn().
=> fixed HER nan warning

baselines/common/models.py
refactor common.models via registering reflection:
1. register default models into `get_network_builder` via `@register` decorator
2. make it more flexible to add new networks in the future
3. docs introducing how to register one's own network into `get_network_builder`
=> refactor common.models via registering reflection

README.md
This way users don't have to navigate out of the documentation to try out the alternative logging.
=> Add tensorboard start command for convenience

baselines/results_plotter.py
You can now also plot `timesteps` *vs.* `episodes`, to see how long the agent lasts before dying.
Default options leave plotting unaltered.
=> Add possibility of plotting timesteps vs episodes

baselines/deepq/replay_buffer.py
The implementation of prioritized experience replay is a bit wrong. To smaple a minibatch of size k, the range [0, p_total] is divided equally into k ranges. Next, a value is uniformly sampled from each range. Finally the transitions that correspond to each of these sampled values are retrieved from the tree. 
Refer to the paper [Prioritized Experience Replay](https://arxiv.org/abs/1511.05952). See Appendix B.2.1 for more details
=> prioritized experience replay bug

baselines/deepq/deepq.py
When trying to use `--play` with DQN:
`python -m baselines.run --alg=deepq --env=SeaquestNoFrameskip-v4 --num_timesteps 0 --play`
It gives the following error:
`TypeError: act() got an unexpected keyword argument 'S'`
Since DQN doesn't use RNNs (which is what I think states and masks are used for?), proposed PR has DQN's `step` function just ignore the `S` and `M` arguments.
=> Fix --play for DQN

baselines/run.py
Training on MuJoCo environments currently uses a default session set up by `run.py`. Currently this session is not set up with `allow_growth = True`, resulting in training taking up all GPU memory available.
I'm also confused why we don't just do `get_session()` here, though, which would just use a `config` with sensible defaults. Why are `intra_op_parallelism_threads=1` and `inter_op_parallelism_threads=1` important here? OK, for MuJoCo environments we default to a single environment, but surely there's no harm in still parallelising TensorFlow computations? (@pzhokhov, as far as I can tell from the git blame, you introduced these lines - maybe you could shed some light?)
Thanks!
=> Set allow_growth=True for MuJoCo sessions

setup.py
the installation of latest mujoco-py fails if mujoco is not present; so baselines that requires gym[mujoco] that requires mujoco-py fails as well.  On the other hand, we don't actually need that for baselines to work
=> disable gym subpackages in setup.py

baselines/common/cmd_util.py, baselines/run.py
this enables, for instance, ppo2 on retro games (related to this: https://github.com/openai/baselines/issues/646)
=> wrap retro envs correctly for other (non-deepq) algorithms

baselines/common/cmd_util.py
As detailed in #670, there was a bug in #669. Simple fix.
=> Fixed TypeError on creating atari vec envs (introduced in #669)

baselines/ddpg/ddpg.py
DeepQ, PPO2, ACER, trpo_mpi, A2C, and ACKTR have the code for:
from baselines.common import set_global_seeds
...
def learn(...):
...
set_global_seeds(seed)
DDPG has the argument 'seed=None' but doesn't have the two lines of code needed to set the global seeds.
=> DDPG has unused 'seed' argument 

baselines/deepq/deepq.py
The `learn` method inside deepq.py had a parameter [`param_noise`](https://github.com/openai/baselines/blob/583ba082a2ade49455030f38374e889874b885fd/baselines/deepq/deepq.py#L116) with no explanation in its docstring. This was now added.
=> Adds description of param_noise parameter in deepq.learn method

baselines/deepq/models.py
`input_` is a better name than `inpt` for  "input" according to PEP8 (https://www.python.org/dev/peps/pep-0008/#naming-conventions)
=> Change variable name from `inpt` to `input_`

baselines/logger.py
This changes the human-readable tabular logger output from ASCII sort order to case-insensitive.
This makes it easier to locate specific values in the table, especially when you are logging lots of values.
=> case-insensitive sort for human-readable logger

baselines/results_plotter.py
Cause of error: Import name must be results_plotter, not log_viewer.
=> Fixed comment on example usage in jupyter-notebook

setup.py
Baselines setup fails when a user has TF nightly builds, this commit fixes that and recognizes nightly builds as valid tf packages.
=> Recognize nightly tf builds

baselines/common/tests/test_tf_util.py, baselines/common/tf_util.py
The fix involves using the placeholder name to crossreference passed
kwargs values, just like the tf_util.function expects. Also, the givens
are updated before the parameters to make it behave like it's supposed
to.
Tested it with the docstring example in tf_util.function.
=> fix #795: Making tf_util._Function consistent

baselines/ppo2/ppo2.py
Both results of following lines are same.
1) `envsperbatch = nenvs // nminibatches` at line:160
2) `envsperbatch = nbatch_train // nsteps`  at line:163
because of `nbath = nenvs * nsteps` and `nbatch_train = nbatch // nminibatches` at line:98-99.
First one is proper because it is more closer to the variable name, `envsperbatch`.
Thank you.
=> remove one of duplicated lines.

baselines/common/cmd_util.py
Fixes the run.py script so that framestack is not applied twice for retro games.
Testing: 
```
from baselines.common.cmd_util import common_arg_parser
from baselines.run import build_env
args = common_arg_parser().parse_args(['--env', 'SpaceInvaders-Snes'])
build_env(args).observation_space
```
now outputs `Box(84, 84, 4)` instead of `Box(84, 84, 16)`.
=> run.py framestack bug fix

baselines/a2c/a2c.py, baselines/a2c/runner.py, baselines/acktr/acktr.py
For A2C and ACKTR, log the average episode reward (`eprewmean`) and episode length (`eplenmean`) over the past 100 episodes in the same way that PPO2 does.
Resolves #469, resolves #606, resolves #851
=> Report episode rewards/length in A2C and ACKTR

baselines/common/tf_util.py
Previously, if one called `get_available_gpus` before the first call to `get_session`, subsequent attempts to create a session would result in the [custom config](https://github.com/openai/baselines/blob/b875fb7/baselines/common/tf_util.py#L63) being ignored. In particular, this would cause Tensorflow to allocate all GPU memory, even though `sess._config` would happily report that `allow_growth` is set to True.
A call to `get_available_gpus` before all other code could be used to assert that the code is running on a GPU at all:
```python
if __name__ == '__main__':
assert get_available_gpus()
```
Also, I took the liberty to make the link to the StackOverflow answer a little bit shorter.
=> Avoid using default config while requesting available GPUs

baselines/ppo2/ppo2.py
CLOCK_MONOTONIC(`time.perf_counter()`) is better than CLOCK_REALTIME(`time.time()`) when observing the duration of two events
=> ppo2: use time.perf_counter() instead of time.time() for time measurement

baselines/common/atari_wrappers.py
In current version, indexing i-th element of LazyFrame return wrong result.
It stores the stacked frame in (height, width, channel) format but using first axis -which is height- when indexing, therefore return value has (width, channel) shape.
----------------
```python
from baselines.common.atari_wrappers import make_atari, wrap_deepmind
env = wrap_deepmind(make_atari('PongNoFrameskip-v4'), frame_stack=True)
state = env.reset()
print(type(state))
print(state[0].shape)
```
The result of above snippet is
```python
<class 'baselines.common.atari_wrappers.LazyFrames'>
(84, 4)
```
for now, but it would be
```python
<class 'baselines.common.atari_wrappers.LazyFrames'>
(84, 84)
```
after the fix.
=> Fix indexing LazyFrames

baselines/common/vec_env/util.py
This PR adds support for Tuple observation spaces. Without this PR, using `VecEnv` with Tuple observation spaces gives the following error:
```
envs = DummyVecEnv(envs)
File "/usr/local/lib/python3.7/site-packages/baselines/common/vec_env/dummy_vec_env.py", line 24, in __init__
self.buf_obs = { k: np.zeros((self.num_envs,) + tuple(shapes[k]), dtype=dtypes[k]) for k in self.keys }
File "/usr/local/lib/python3.7/site-packages/baselines/common/vec_env/dummy_vec_env.py", line 24, in <dictcomp>
self.buf_obs = { k: np.zeros((self.num_envs,) + tuple(shapes[k]), dtype=dtypes[k]) for k in self.keys }
TypeError: 'NoneType' object is not iterable
```
=> Support Tuple observation spaces

baselines/logger.py
Only print the "logging to [dir]" message when the logger has something to output. Running with the new spawn change and both mpi and subprocvecenv, there are many "logging to [dir]" messages but most are not logging anything.
=> suppress excessive messages from unused loggers

baselines/common/vec_env/shmem_vec_env.py
"self.waiting_step" is initialized in __init__ function but it is not reassigned anywhere.
Because it is used in reset function and close_extras function, it should be fixed.
So i fixed it to be similar with subproc_vec_env's one.
=> Starting to reassign waiting_step in shmem_vecenv

baselines/common/atari_wrappers.py
Fix for issue #892. PR #875 changed behavior of \_\_getitem\_\_ method of [LazyFrames ](https://github.com/openai/baselines/blob/9b68103b737ac46bc201dfb3121cfa5df2127e53/baselines/common/atari_wrappers.py#L229) class. So, numpy wasn't able to convert list of LazyFrames instances in an [util method](https://github.com/openai/baselines/blob/9b68103b737ac46bc201dfb3121cfa5df2127e53/baselines/common/tf_util.py#L394).
I offer to reverse changes from #875, and introduce interface for getting count of frames and specific frames for LazyFrames instance.
Example of usage:
```python
import numpy as np
from baselines.common.atari_wrappers import make_atari, wrap_deepmind
env = wrap_deepmind(make_atari('PongNoFrameskip-v4'), frame_stack=True)
state = env.reset()
print(type(state)) …
```
=> Fix converting list of LazyFrames to ndarray

README.md, baselines/common/cmd_util.py, baselines/logger.py, baselines/run.py
as directed by the README, the command 
`python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7 --save_path=~/models/pong_20M_ppo2
`
saves the learning curve logs by default to `/tmp/`, or otherwise set by the env variable `$OPENAI_LOGDIR`. This was not immediately obvious to me, so I thought it would improve the command-line usage to include a flag for specifying the log directory. Additionally, since both `save_path` and `load_path` rely on flags and not on env variables, I thought it would be best to keep `log_path` in line with that same functionality/behavior.
=> add log_path flag to command line utility

baselines/run.py
Hello!
With a recent commit in openai gym (openai/gym@dc91f43) the entry_point variable was changed from private to public, thus breaking baselines/baselines/run.py script.
Updating baselines/run.py in lines 35 and 129 from
env_type = env._entry_point.split(':')[0].split('.')[-1]
to
env_type = env.entry_point.split(':')[0].split('.')[-1]
fixes this problem. I hope, this can be useful.
Best regards,
Nico Bach
=> entrypoint variable made public

baselines/common/mpi_moments.py
(send pickled data instead of floats) - probably affects performance somewhat, but avoid element number mismatch. Fixes 998
=> use allreduce instead of Allreduce 

baselines/acer/acer.py
There is bug in acer algorithm to save and load trained models. At first, train the model using acer method and save it. Then load the saved mode. The model did not learn anything and seems to be a random or initial model.
It could be tested by the following case:
OPENAI_LOGDIR=$HOME/logs/cartpole-acer-ori OPENAI_LOG_FORMAT=tensorboard python -m baselines.run --alg=acer --env=CartPole-v0 --num_timesteps=1e5 --nsteps=32 --save_path=~/models/choice_acer-ori
python -m baselines.run --alg=acer --env=CartPole-v0 --num_timesteps=0 --nsteps=32 --load_path=~/models/choice_acer-ori --play
The tensorborad shows that  the mean reward per episode is around 200 at the end of training.  But the load and visualize model shows that the mean reward per episode is around 22 which could be done by random …
=> fix a bug in acer saving and loading model

baselines/common/vec_env/subproc_vec_env.py
Sometimes env's specs contain data, that cannot be pickled using `pickle` (e.g. lambdas). Wrapping `get_spaces_spec` return with `CloudpickleWrapper` solves this problem.
=> Use CloudpickleWrapper to send specs in SubprocVecEnv

baselines/bench/monitor.py
In my work I have used a monitored environment which has some resources it needs to close. Using Monitor was the problem as it doesn't call close() on its parent. This fixes it
=> Monitor should close what it inherits
