baselines/common/tf_util.py
Noticed these while getting familiar with the repository.
Not sure if updates would be welcome or not :question:
=> tf_util: spelling / docstring updates

baselines/deepq/README.md
Just a proposal to find a better way to link the experiments so they can be more simpler to find
=> Adding links to source files

baselines/trpo_mpi/trpo_mpi.py
The TRPO implementation calculates standardized advantages but then it doesn't use them. This fixes it.
=> Use standardized advantages in trpo.

baselines/acktr/acktr_cont.py, baselines/acktr/run_mujoco.py, baselines/acktr/value_functions.py
Fixes the NaN issues people been reporting https://github.com/openai/baselines/issues/127 as well as small tweaks together with fixing bug in run_mujoco.py (replacing env_id with env) 
@joschu i would appreciate if you could merge this pull request. thanks.
=> Fixes the NaN issues in ACKTR + bug in run_mujoco.py

baselines/acktr/kfac.py, baselines/common/atari_wrappers.py
=> fix misspellings

baselines/deepq/experiments/atari/enjoy.py
See https://github.com/openai/gym/blob/master/README.rst
In "What's new" it says: 
> Moved gym/monitoring to gym/wrappers/monitoring
So I updated the import of videorecorder accordingly
=> updated videorecorder import

baselines/acer/acer_simple.py
=> Bug fix in saving ACER model

baselines/a2c/a2c.py, baselines/a2c/policies.py, baselines/a2c/utils.py, baselines/acer/acer_simple.py, baselines/acktr/run_atari.py, baselines/common/__init__.py, baselines/common/atari_wrappers.py, baselines/common/cmd_util.py, baselines/common/distributions.py, baselines/common/mpi_moments.py, baselines/common/segment_tree.py, baselines/common/tests/test_tf_util.py, baselines/common/tf_util.py, baselines/common/vec_env/__init__.py, baselines/common/vec_env/dummy_vec_env.py, baselines/deepq/experiments/run_atari.py, baselines/deepq/replay_buffer.py, baselines/logger.py, baselines/ppo2/policies.py, baselines/ppo2/ppo2.py, baselines/ppo2/run_atari.py
should address https://github.com/openai/baselines/issues/364, https://github.com/openai/baselines/issues/357, https://github.com/openai/baselines/issues/345,
=> import rl-algs

baselines/deepq/README.md
Atari example URL seems still point to old files
=> Update Atari example URL

README.md
The headline mentions PPO, but the command was for A2C
=> Updated example commands to run ppo2

baselines/trpo_mpi/trpo_mpi.py
for compatibility with other algos
=> rename entcoeff to ent_coef in trpo_mpi 

baselines/a2c/README.md, baselines/a2c/a2c.py, baselines/a2c/runner.py, baselines/common/policies.py, baselines/ppo2/ppo2.py
Hi,
1. I've added some comments in A2C implementations **to help the users to better understand this implementation. I tried to be succinct.**
--> I think it can help readers who try **to modify the implementations or really understand them.**
2. Also, I've modified the **readme file to explain rapidly what each file do.**
The new baseline version **is really good**. However I think we can improve readme part, or what if include a wiki part **to describe the different architectures with schemas, because it can helps users to have the big picture in mind** (what file does what, what is the process etc). [Like the schema I made for the former PPO2 version](http://bit.ly/2DsbsSe) but not as ugly as mine version 😂 (this is a draft).
=> Wrote some comments to explain the A2C and PPO2 implementation

baselines/a2c/a2c.py, baselines/a2c/runner.py, baselines/common/policies.py, baselines/ppo2/ppo2.py
Hi,
Given @jachiam feedback, I modified the comments that **explains A2C and PPO implementations**.
=> Updated A2C and PPO2 comments

baselines/deepq/utils.py, baselines/run.py
the problem was input was scaled twice - once by the ScaledFloatFrame Wrapper, once by the neural net code.
=> fix DQN learning bug

baselines/acer/acer.py, baselines/acer/buffer.py, baselines/acer/runner.py, baselines/common/tests/test_cartpole.py, baselines/common/tests/test_identity.py, baselines/common/tests/test_mnist.py, baselines/common/tests/test_serialization.py, baselines/run.py
make ACER use VecFrameStack wrapper instead of internal stacker, 
make it compatible with non-image observations, 
cartpole test
=> refactor ACER

baselines/ppo2/defaults.py
Created defaults for retro, copied from Atari defaults for now. Tested with SuperMarioBros-Nes
=> Add retro to ppo2 defaults

baselines/common/tf_util.py
Added documentation to the "updates" parameter of tf_util.function.
I'm not very familiar with tf and it confused me for a bit when I first read that code, hopefully this documentation addition will avoid that for other users.
=> Parameter documentation for tf_util.function

baselines/common/atari_wrappers.py
This PR just fixes a typo in a comment.
=> fixes typo

baselines/acer/acer.py
=> Added required arguments to the policy builder in the ACER model to

baselines/gail/adversary.py, baselines/gail/dataset/mujoco_dset.py
Fix bugs in GAIL, see https://github.com/openai/baselines/issues/802 for more details
=> fix bugs: obs_ph normalization in adversary.py

baselines/common/plot_util.py
Remove the comma behind the last input argument
=> fix a small bug in plot_results()

baselines/deepq/utils.py
`TfInput` is an interface class used to deal with a placeholder.
I add `self` argument of  the class as its subclass.
Thanks!
=> fix the definition of `TfInput.make_feed_dict`.

baselines/deepq/experiments/custom_cartpole.py
=> Interface for U.make_session changed

baselines/common/misc_util.py
A proposal for a clean-up, as it seems these two functions are rarely used.
=> [Update misc_util.py]: clean up unused helper functions

baselines/common/mpi_adam_optimizer.py
=> remove f strings for python back compatibility

baselines/bench/__init__.py, baselines/bench/benchmarks.py, baselines/bench/monitor.py, baselines/bench/test_monitor.py, setup.cfg
run test_monitor through pytest; fix the test, add flake8 to bench directory - like PR 891
=> like PR 891

setup.py
Updating the version in setup.py to avoid conflict with the old (>1 year old) version in pypi.
=> Updating the version to 0.1.6

baselines/gail/dataset/mujoco_dset.py
=> Fix typo in GAIL dataset log

baselines/gail/behavior_clone.py, baselines/gail/run_mujoco.py
=> Fix behavior cloning due to API changes

setup.py
Setup will now install latest tf2 and latest compatible gym.
=> tf2: Updated setup.py dependencies.
